### ISSUE TITLE
No matching distribution found for crypto-condor

### ISSUE THREAD

**Issue by christophedumont5** [quarkslab/crypto-condor#1]
No matching distribution found for crypto-condor
pip version : pip 9.0.3 from /usr/lib/python3.6/site-packages (python 3.6)
oracle linux 8
python version : 3.6.8

**Comment by pcotret** [comment]
Had the same problem.
Once you install the pip requirements as it can be seen at https://github.com/quarkslab/crypto-condor/blob/main/pyproject.toml#L54-L63, it can be installed.

**Comment by JulioLoayzaM** [comment]
Hi @christophedumont5, indeed crypto-condor requires Python 3.11, I've updated the README. I think it can be lowered to 3.10 with a few changes but we do not plan on supporting any version below that. I can suggest using [pyenv](https://github.com/pyenv/pyenv) to install a recent version of Python and install crypto-condor in a virtual environment to use the library and CLI, or combine pyenv with [pipx](https://pipx.pypa.io/stable/) to install the CLI.

**Comment by JulioLoayzaM** [comment]
And hi @pcotret, your issue seems related to #2 so I'll respond there to close this one.
